# Pi-hole Helm Chart Values

# This gives Pi-hole its own IP on your LAN so you can point your Router to it.
serviceDns:
  type: LoadBalancer
  # If you want a specific IP (and your K3s LoadBalancer supports it), uncomment below:
  # loadBalancerIP: 192.168.1.50 
  annotations:
    # If using MetalLB, this allows sharing the IP with the Web service
    metallb.universe.tf/allow-shared-ip: "pihole-svc"

serviceWeb:
  # Use LoadBalancer to access via IP (http://192.168.x.x/admin)
  # Use ClusterIP if you are using the Ingress we set up earlier
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole-svc"

persistentVolumeClaim:
  enabled: true
  size: 1Gi
  # storageClass: "local-path" # K3s default is usually 'local-path'


  # These are the servers Pi-hole asks if it doesn't know the domain
dnsmasq:
  customDnsNameservers:
  - 1.1.1.1
  - 8.8.8.8
